### ISSUE TITLE
关于如何理解“the pseudo label is generated by forwarding source-like images to the well-trained source model.”

### ISSUE THREAD

**Issue by yyw13791768446** [CityU-AIM-Group/SFDA-FSM#10]
1、我将目标域的labels图像放在了domain_inversion.py中利用源模型生成了如下图像
![b47414c42472219f3324f1b3fc3f0fa](https://github.com/CityU-AIM-Group/SFDA-FSM/assets/57339973/b603e264-6299-4166-9dfe-6149a8224d77)
但我训练时发现效果错误，请问对于pseudo label这部分具体的处理步骤是怎么样的呢？
![a3aca1ada7e2a26ad9adb44290a1962](https://github.com/CityU-AIM-Group/SFDA-FSM/assets/57339973/27f11bd4-b94a-47a7-857a-89290c6acc94)
2、在test.py里面我注意到如下两个路径下的文件，请问他们是如何生成的？
![b319891becfdde2a7bbc995121e88c1](https://github.com/CityU-AIM-Group/SFDA-FSM/assets/57339973/02701af0-e847-4ccf-8be3-7cca3457ab45)
感谢您的分享！

**Comment by cyang-cityu** [comment]
Thanks for your interest to our work.
1. The pseudo label is generated by forwarding source-like images to the source model.
2. The adabn_list is the same as test_list. RESTORE_FROM is the path of model you want to test.

**Comment by yyw13791768446** [comment]
请问能否把“The pseudo label is generated by forwarding source-like images to the source model.”这一部分的程序脚本分享下呢？谢谢！
