### ISSUE TITLE
About coarse genneration and fine genneration in the paper

### ISSUE THREAD

**Issue by henryccl** [CityU-AIM-Group/SFDA-FSM#2]
Hi I tried to use this code for a domain adaptation study on a polyp dataset, but ran into some problems.

I followed the suggestion in the paper to use the source domain model to convert the noise to a coarse genneration of the source-like style. Then I used the coarse genneration and the target domain image to perform a Fourier transform to obtain the fine genneration.

However, the generated coarse generation is still noisy and there is still a significant difference between the style of the generated fine generation and the actual target domain.

I would like to know if it is normal to have such coarse generation, and fine generation?
![image](https://user-images.githubusercontent.com/44051761/205795339-6bfcb50e-2ec6-42dc-b7ea-8d2ee69e0780.png)
![image](https://user-images.githubusercontent.com/44051761/205795392-a1763f4d-bb8d-418c-9672-be83c2351b97.png)

**Comment by cyang-cityu** [comment]
You can try to initialize the input noise with original target data. It will be much easier to convergence.

**Comment by henryccl** [comment]
Thank you for your answer！
