### ISSUE TITLE
Some Question About pseudo

### ISSUE THREAD

**Issue by zqp1226358** [CityU-AIM-Group/SFDA-FSM#5]
Hello，I want to ask what kind of data is put in the pseudo folder, how is it generated, it seems that I don't see the relevant code implementation

![image](https://github.com/CityU-AIM-Group/SFDA-FSM/assets/47075652/6eb501bb-509a-4d08-bb16-0fd60c844d2a)

![image](https://github.com/CityU-AIM-Group/SFDA-FSM/assets/47075652/5b19960e-7b04-44f1-9dfc-1eccbca5acdf)

**Comment by cyang-cityu** [comment]
Hi, the pseudo label is generated by forwarding source-like images to the well-trained source model.

**Comment by zqp1226358** [comment]
Hello, thank you for your reply.
Currently I run the code but the result is not what I expected. 

![image](https://github.com/CityU-AIM-Group/SFDA-FSM/assets/47075652/e6b71327-802d-46e3-8806-00da2e1bf856)

I suspect that there is still a problem with my preprocessing？
the coarse_generation is as follows
![image](https://github.com/CityU-AIM-Group/SFDA-FSM/assets/47075652/80a2dd1c-2f9a-4a1a-9b07-728d71a21d5e)

the fine_generation is as follows
![image](https://github.com/CityU-AIM-Group/SFDA-FSM/assets/47075652/61059a71-cc06-43d0-adfe-ca0fdc717152)

the pseudo label is as follows,  I pass in the source-like image to the pretrained model you provided
![image](https://github.com/CityU-AIM-Group/SFDA-FSM/assets/47075652/06ae2840-e8ae-41fe-8ab2-4b40ad25c39e)

In addition, The "resnet_pretrain.pth" is missing, Is it convenient for you to provide it?

Looking forward to your reply. Thank you very much.

**Comment by yyw13791768446** [comment]
> Hi, the pseudo label is generated by forwarding source-like images to the well-trained source model.

您好，请问一下这个pseudo label 是怎么生成与应用的呢？
