### ISSUE TITLE
关于预训练权重

### ISSUE THREAD

**Issue by yyw13791768446** [CityU-AIM-Group/SFDA-FSM#8]
您好，/home/cyang/SFDA/checkpoint/resnet_pretrain.pth这个模型路径下的权重文件能分享一下吗？谢谢！

**Comment by cyang-cityu** [comment]
@yyw13791768446 You can download from this link [resnet pretrained model](https://drive.google.com/file/d/1LS_5gRc9B0-BXf_OrZfVbidn0JmNHrws/view?usp=sharing).
