### ISSUE TITLE
The third part of the article mentions style_loss, content_loss, contrastive_loss, distillation_loss. I can understand them on a mathematical level, but I'm not very clear on how to implement them in code. Can I see how you guys do it?

### ISSUE THREAD

**Issue by maoyugougu** [CityU-AIM-Group/SFDA-FSM#9]

**Comment by cyang-cityu** [comment]
Thanks for your interest to our work. 
1. The style loss and content loss are utilized to achieve domain inversion. You can refer to them on 'tools/domain_inversion.py' part with loss_content and loss_r_feature. 
2. The contrastive loss and distillation loss is applied for domain adaptation. You can refer to them on 'tools/train_adapt.py'.
